POST http://localhost:7000/api/users/register
Content-Type: application/json

{
    "firstname": "LoganZ",
    "lastname": "Nguyen",
    "email": "ln26805@gmail.com",
    "password": "alooo"
}

### 

POST http://localhost:7000/api/checkAuthorized
Content-Type: application/json

{
    "accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDBmNGMxZGZiMDcwOTExN2MyNDI3ZGYiLCJpYXQiOjE2Nzg3MjQxMjUsImV4cCI6MTY3ODgxMDUyNX0.v5Bw_YSu7NCE7hgXUFhu07gZqS1XDFZ6jTnI-m5ZvZE"
}